id: A70F65B24
base_file: f12A8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:13:38.923606
  last_modified_at: 2022-05-31 05:13:38.923613
